### ISSUE TITLE
not an issue but a general question

### ISSUE THREAD

**Issue by Jerryaa98** [nianticlabs/nerf-object-removal#13]
Hi, Great work.
I am doing a project where I need to take pictures of  a certain object while my hand is covering some of the object in different areas in different images, and I need a model to remove the hands and make an accurate picture of the module suing nerf, will your code help do that? or does it remove only a single object like the rock in the examples?

**Comment by mdfirman** [comment]
Hi @Jerryaa98 ,

Thanks for your interest!

In your scenario, will the hand be in different places in each of the images? I.e. will different parts of the object be covered in each image?

If so, you might not need our full method, but might instead be able to use a more simple 'masked nerf'. I.e. do the following steps:

1. Get a mask of the hands in each input image (e.g. using semantic segmentation)
2. Train a nerf, but avoid training on the pixels which have been masked in the step above.

This is equivalent to the 'masked Nerf' baseline in our paper.


<img width="675" alt="image" src="https://github.com/nianticlabs/nerf-object-removal/assets/6114258/9df96e1f-90a6-474e-83e6-25420b097cb4">


The reason you might not need our full method is because our method is really designed for when the object you want to remove is static, and so is in the same position in each input image. This makes the inpainting harder, hence why we need a 2D inpainting method.

**Comment by Jerryaa98** [comment]
Thanks for your help, yes the hands will be covering different types of the model in each image, therefore this might work perfectly.
Appreciate it
